Added some more API commands
theta360developers/theta-javascript pull request #8
Opened 2023-05-15 19:39 UTC by AirTechWick

2023-05-15 23:01 UTC, codetricity requested changes
output of listFiles should be a readable string.  Use stringify to convert object to string in listFiles.js

2023-05-15 23:01 UTC, codetricity commented on fake-theta/commands/listFiles.js
> +console.log(data);
use stringify to print out the contents of a JavaScript object to a json string

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify

```javascript
console.log(JSON.stringify(data, null, 4))
```

Refer to the last line of this example:

https://github.com/theta360developers/theta-javascript/blob/main/fake-theta/examples/lastThumbUrl.js

2023-05-16 16:29 UTC, AirTechWick commented
Fixed requested changes

2023-05-16 17:43 UTC, jcasman approved these changes
Well done! Great use of `stringify`.

2023-05-16 17:51 UTC, codetricity approved these changes
good.  FYI, the number 4 is the number of spaces for the indent of the formatted JSON string output.  If you just use `JSON.stringify(data)`, it will still work, but will not be formatted.  Just in case you want to practice with stringify.

2023-05-16 17:51 UTC, merged

2023-05-16 17:52 UTC, codetricity commented
I merged it because @jcasman was in a meeting and it looks like he reviewed it immediately before me.  in general, jesse should merge the pull request after review.

2023-05-16 17:59 UTC, jcasman commented
Thank you!